### ISSUE TITLE
Why Is Your Readme Written Like This

### ISSUE THREAD

**Issue by ghost** [CodedIsTaken/Obsidian-Web-Browser#1]
I Would Advise Against Capitalizing Every Word - unless you want to break the reading flow of every person ever

also it contains grammatical errors

Best of luck!

**Comment by ghost** [comment]
additionally, please codeblock your commands

sandwich a line(s) with ```, just like so:

\```
i'm a code block
\```

turns into

```
i'm a code block
```

**Comment by CodedIsTaken** [comment]
i'm looking into this advise, thanks.

**Comment by CodedIsTaken** [comment]
most likely due to my disability, i read This, normally.
